// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package complexity_sample

type Circle struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Event Event  `json:"event"`
}

type Event struct {
	ID         string   `json:"id"`
	Name       string   `json:"name"`
	CircleList []Circle `json:"circleList"`
}
